### ISSUE TITLE
Address integrator issue (Cross database associations)

### ISSUE THREAD

**Issue by devinivy** [balderdashy/sails#5491]
A potential issue with the integrator was brought-up by @particlebanana in https://github.com/balderdashy/waterline/issues/664#issuecomment-57248273 , issue #664.  This is a technical issue that needs review and a potential fix.  If @particlebanana could chime-in what exactly to look for, that would be very useful!

**Pending tasks:**
- [x] 1. PR #984 merged
- [x] 2. PR #985: unit tests may need to be revised 
- [x] 3. PR balderdashy/sails-mysql#212 merged
- [x] 4. PR balderdashy/sails-postgresql#158 merged
- [x] 5. balderdashy/waterline-adapter-tests#64
  - [x] Enable cross-adapter tests in sails-mongo balderdashy/sails-mongo#282
  - [x] Enable cross-adapter tests in sails-memory balderdashy/sails-memory#22
  - [x] Enable cross-adapter tests in sails-disk balderdashy/sails-disk#43
  - [x] Enable cross-adapter tests in sails-mysql balderdashy/sails-mysql#221
  - [x] Enable cross-adapter tests in sails-postgresql balderdashy/sails-postgresql#160
- [x] 6. Fix Populate m:m cross adapter/connection issue #1014
