### ISSUE TITLE
Add adapter tests to waterline core

### ISSUE THREAD

**Issue by dmarcelino** [balderdashy/sails#5561]
Add adapter tests to waterline core to ensure changes in waterline don't break adapters.

Tasks:
- [x] add a set of adapter tests to waterline core suite of tests (always exit 0 for now): #896;
- [x] Make sure waterline-adapter-tests is using correct WL dependency: #914;
- Fix sails-memory, currently it's breaking a couple of tests, check [here](https://travis-ci.org/dmarcelino/waterline-adapter-tests/jobs/55738380#L326): balderdashy/sails-memory#18:
  - [x] "Semantic Interface .find() should escape attribute names to prevent SQL injection attacks": balderdashy/waterline-adapter-tests#40;
  - [x] "Semantic Interface .findOrCreateEach() should only have a single record for keys that exist": #905.
- [x] Once sails-memory is fixed make the adapter tests exit with 1 on error: #941

More details at PR #896.
