### ISSUE TITLE
[Feature Request] New migration strategy: "create"

### ISSUE THREAD

**Issue by dmarcelino** [balderdashy/sails#5580]
Hi,

I've started to play with "migratable" interface on [waterline-orientdb](https://github.com/appscot/waterline-orientdb) and one of the things I've noticed is that "migratable" doesn't have an option to "safely alter" the database. By this I mean not performing any destructive operations (drops) but creating any tables/columns (through `define()`/`addAttribute()`) that were added to the schema. I believe such strategy would make sense, even in production as most times we want new tables/columns to be added. The advantage of such strategy in production is reducing manual intervention (which is error prone).

To give an example from real life, in my previous job (a multinational bank), we would rarely drop tables or delete columns from shared databases (few would bother with the risk, bureaucracy, chasing other teams, etc) but we would frequently add tables and columns.

I suggest we add a new strategy called `create` that will only perform the additive operations. I say "we" as I don't mind contributing to this provided the maintainers agree to the change.
## Tasks:
- [x] add migration strategy `create` #853
- [ ] adds tests for migration strategy `create` balderdashy/waterline-adapter-tests#34
- [x] Add "create" migration to adapter-specification.md balderdashy/sails-docs#427
- [ ] After/if `'create'` is added to Sails.js, update https://github.com/balderdashy/sails-docs/blob/master/concepts/ORM/model-settings.md

PS: I've searched for this in the issues but couldn't find anything, if there is an issue on the same topic redirect me and I'll comment there.
PPS: Initially I called this strategy "alter-safe" but after sleeping on it (literally) I arrived to the conclusion that "create" is a better name and falls in nicely with the other strategies : `drop`, `alter`, `create`, `safe`.
